version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - /apps/api
      - /packages/shared-models
    schedule:
      interval: 'weekly'
      day: sunday
    cooldown:
      default-days: 14
    versioning-strategy: increase
    groups:
      security:
        dependency-type: development
        applies-to: security-updates
      deps:
        dependency-type: development
        applies-to: version-updates
    labels:
      - dependencies

  - package-ecosystem: 'npm'
    directories:
      - /apps/client
    schedule:
      interval: 'weekly'
      day: sunday
    cooldown:
      default-days: 14
    versioning-strategy: increase
    groups:
      security:
        dependency-type: development
        applies-to: security-updates
      deps:
        dependency-type: development
        applies-to: version-updates
    labels:
      - dependencies

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    open-pull-requests-limit: 1
    labels:
      - dependencies
