packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - bcrypt

catalog:
  zod: 4.1.12
  '@faker-js/faker': 9.9.0
  oxlint: 1.60.0
  'oxlint-tsgolint': 0.22.0

preferFrozenLockfile: true
ignoreDepScripts: true
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  # Renovate security update: @nestjs/core@11.1.18
  - "@nestjs/core@11.1.18"
