packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - bcrypt

catalog:
  zod: 4.1.12

preferFrozenLockfile: true
ignoreDepScripts: true
minimumReleaseAge: 10080 # 7 days
