packages:
  - apps/*
  - packages/*

catalog:
  zod: 4.1.12
  '@faker-js/faker': 9.9.0
  oxlint: 1.60.0
  'oxlint-tsgolint': 0.22.0

preferFrozenLockfile: true
minimumReleaseAge: 10080 # 7 days
overrides:
  node-xlsx>xlsx: '-'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': false
  '@swc/core': true
  '@prisma/engines': false
  '@scarf/scarf': false
  '@sentry/cli': false
  bcrypt: true
  prisma: false
  puppeteer: false
  unrs-resolver: false
  esbuild: true
minimumReleaseAgeExclude:
  # Renovate security update: react-router@7.15.0 || 7.15.1
  - react-router@7.15.0 || 7.15.1
