export enum FileType {
  PIECE_JOINTE_TRANSPARENCE = 'PIECE_JOINTE_TRANSPARENCE',
  PIECE_JOINTE_TRANSPARENCE_POUR_PARQUET = 'PIECE_JOINTE_TRANSPARENCE_POUR_PARQUET',
  PIECE_JOINTE_TRANSPARENCE_POUR_SIEGE = 'PIECE_JOINTE_TRANSPARENCE_POUR_SIEGE',
}
