services:
  postgres:
    image: 'postgres:13.2'
    ports:
      - '5440:5432'
    networks:
      - app_net
    user: postgres
    environment:
      POSTGRES_USER: fondation
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fondation

networks:
  app_net:
    driver: bridge
