name: Build and upload client artifact

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tag:
        type: string
        required: true
    secrets:
      VITE_SENTRY_DSN:
        required: false
      SENTRY_CLIENT_AUTH_TOKEN:
        required: false

jobs:
  build-client:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-tags: true
          fetch-depth: 200

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
        with:
          version: 11.5.0
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: '24.12.0'
          cache: 'pnpm'

      - name: install sheetjs
        shell: bash
        run: ./scripts/sheetjs.sh

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build DSFR
        run: pnpm --filter client run update-icons

      - name: Cached fonts
        id: cached_fonts
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: apps/client/src/assets/fonts
          key: assets-montserrat-7.222_noto-2.015

      - name: Download Fonts
        if: steps.cached_fonts.outputs.cache-hit != 'true'
        shell: bash
        run: apps/client/scripts/install-fonts.sh

      - name: Build client
        run: pnpm --filter client... build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_DEPLOY_ENV: ${{ vars.VITE_DEPLOY_ENV }}
          VITE_GDS_TRANSPA_FILES_IDS: ${{ vars.VITE_GDS_TRANSPA_FILES_IDS }}
          VITE_JDMA_URL: ${{ vars.VITE_JDMA_URL }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_TAGGED_VERSION: ${{ inputs.tag }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_CLIENT_AUTH_TOKEN }}

      - name: Create Archive
        run: |
          # In Scalingo dashboard, we set the PROJECT_DIR environment variable to client
          mkdir -p scalingo/client
          cp -r apps/client/dist "$_"
          cp -r apps/client/scalingo/* "$_"
          cp apps/client/scalingo/.buildpacks "$_"
          tar -czf client-scalingo.tar.gz scalingo

      - name: Upload as Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          retention-days: 1
          name: client-scalingo-${{ inputs.tag }}
          path: client-scalingo.tar.gz
