name: Build and upload web artifact

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tag:
        type: string
        required: true
    secrets:
      VITE_FAKE_USERS:
        required: true

jobs:
  build-and-deploy-webapp-artifact:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.11.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build webapp
        run: pnpm --filter webapp... build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_FAKE_USERS: ${{ secrets.VITE_FAKE_USERS }}

      - name: Create Archive
        run: |
          # In Scalingo dashboard, we set the PROJECT_DIR environment variable to webapp
          mkdir -p scalingo/webapp
          cp -r apps/webapp/dist "$_"
          cp -r apps/webapp/scalingo/* "$_"
          cp apps/webapp/scalingo/.buildpacks "$_"
          tar -czf webapp-scalingo.tar.gz scalingo
      - name: Archive dist
        uses: actions/upload-artifact@v4
        with:
          name: webapp-scalingo-${{ inputs.tag }}
          path: webapp-scalingo.tar.gz
