name: "Continuous Delivery"

on:
  push:
    branches:
      - main
  # Temporary, to trigger the workflow manually while creating the API CI/CD
  workflow_dispatch:

jobs:
  integration-checks:
    uses: ./.github/workflows/integration-checks.yml

  build-and-upload-api-artifact:
    needs: [integration-checks]
    uses: ./.github/workflows/build-and-upload-api-artifact.yml
    with:
      tag: "v${{ github.run_number }}"
  build-and-upload-webapp-artifact:
    needs: [integration-checks]
    uses: ./.github/workflows/build-and-upload-webapp-artifact.yml
    with:
      tag: "v${{ github.run_number }}"

  deploy-staging:
    name: Deploy staging
    needs: [build-and-upload-api-artifact, build-and-upload-webapp-artifact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      environment: staging
      tag: "v${{ github.run_number }}"
    secrets: inherit
