name: Deploy application on scalingo

on:
  workflow_call:
    inputs:
      tags_current:
        type: string
        required: true

      tags_previous:
        type: string
        required: false

      environment:
        type: string
        required: true
    secrets:
      SCALINGO_API_TOKEN:
        required: false

jobs:
  deploy:
    name: "Deploy to ${{ inputs.environment }}"
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.environment }}

    steps:
      - name: Download api artifact
        uses: actions/download-artifact@v4
        with:
          name: api-scalingo-${{ inputs.tags_current }}

      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          name: client-scalingo-${{ inputs.tags_current }}

      - name: Install scalingo CLI
        run: |
          curl -O https://cli-dl.scalingo.com/install && bash install
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Login to scalingo
        run: scalingo login --api-token ${{ secrets.SCALINGO_API_TOKEN }}

      - name: Update remote version envvar
        run: scalingo --region ${{ vars.SCALINGO_APP_REGION }} --app ${{ vars.SCALINGO_API_APP_NAME }} env-set APP_VERSION=${{ inputs.tags_current }}

      - name: Migrate db
        shell: bash
        run: bash ./apps/api/scripts/

      - name: Deploy api
        run: |
          echo "Deploying api on app ${{ vars.SCALINGO_API_APP_NAME }}"
          scalingo --region ${{ vars.SCALINGO_APP_REGION }} --app ${{ vars.SCALINGO_API_APP_NAME }} deploy api-scalingo.tar.gz

      - name: Deploy client
        run: |
          echo "Deploying client on app ${{ vars.SCALINGO_CLIENT_APP_NAME }}"
          scalingo --region ${{ vars.SCALINGO_APP_REGION }} --app ${{ vars.SCALINGO_CLIENT_APP_NAME }} deploy client-scalingo.tar.gz
