name: "Deploy production"

on:
  workflow_dispatch:

jobs:
  integration-checks:
    uses: ./.github/workflows/integration-checks.yml

  build-and-upload-api-artifact:
    needs: [integration-checks]
    uses: ./.github/workflows/build-and-upload-api-artifact.yml
    with:
      tag: "v${{ github.run_number }}"

  build-and-upload-webapp-artifact:
    needs: [integration-checks]
    uses: ./.github/workflows/build-and-upload-webapp-artifact.yml
    with:
      environment: production
      tag: "v${{ github.run_number }}"
    secrets: inherit

  deploy-production:
    name: Deploy production
    needs: [build-and-upload-api-artifact, build-and-upload-webapp-artifact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      environment: production
      tag: "v${{ github.run_number }}"
    secrets: inherit