name: Integration checks

on:
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    secrets:
      SCW_SECRET_KEY:
        required: true
      SCW_ENCRYPTION_KEY:
        required: true
jobs:
  build:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.11.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build the shared models, necessary for the type checks
        run: pnpm --filter shared-models build
      - name: Types check
        run: pnpm types:check
      - name: Lint
        run: pnpm lint:check
      - name: Format
        run: pnpm format:check
      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps msedge chromium chrome
      - name: Test
        run: pnpm test:all
        env:
          SCW_ACCESS_KEY: ${{ vars.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_ENCRYPTION_KEY: ${{ secrets.SCW_ENCRYPTION_KEY }}
          S3_REPORTS_ATTACHED_FILES_BUCKET: ${{ vars.S3_REPORTS_ATTACHED_FILES_BUCKET }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      - name: Build
        run: pnpm build
