name: Migrate Db
permissions:
  contents: read

on:
  workflow_call:
    secrets:
      SCALINGO_API_TOKEN:
        required: false
      SCALINGO_SSH_KEY:
        required: false

    inputs:
      environment:
        type: string
        required: true
      tags_current:
        type: string
        required: true
      tags_previous:
        type: string
        required: false

jobs:
  migrate:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-depth: 200
          fetch-tags: true

      - uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323
        id: changed-files
        with:
          sha: ${{ inputs.tags_current }}
          base_sha: ${{ inputs.tags_previous }}
          files: |
            apps/api/prisma/migrations/**/*.sql

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          version: 11
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          node-version: '24.12.0'
          cache: 'pnpm'

      - name: Install scalingo CLI
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          token: ${{ secrets.SCALINGO_API_TOKEN }}
        run: |
          curl -O https://cli-dl.scalingo.com/install && bash install
          echo "$HOME/bin" >> $GITHUB_PATH
          scalingo login --api-token ${token}

      - name: Run migration
        if: steps.changed-files.outputs.any_changed == 'true'
        shell: bash
        env:
          SCALINGO_APP_REGION: ${{ vars.SCALINGO_APP_REGION }}
          SCALINGO_API_APP_NAME: ${{ vars.SCALINGO_API_APP_NAME }}
          SCALINGO_SSH_KEY: ${{ secrets.SCALINGO_SSH_KEY }}
          SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
        run: ./apps/api/scripts/migrate.sh
