name: 'Deploy production'
permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:

jobs:
  release:
    if: github.ref_type == 'branch' && github.ref_name == 'production'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      environment: production
