name: "Release"
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        description: "'staging' or 'production'"
        required: true
        type: string

    outputs:
      tags_current:
        value: ${{ jobs.tags.outputs.current }}
      tags_previous:
        value: ${{ jobs.tags.outputs.previous }}

    secrets:
      VITE_SENTRY_DSN:
        required: false
      SCALINGO_API_TOKEN:
        required: false
      SENTRY_API_AUTH_TOKEN:
        required: false
      SENTRY_CLIENT_AUTH_TOKEN:
        required: false
      SCALINGO_SSH_KEY:
        required: false

jobs:
  tags:
    uses: ./.github/workflows/tags.yml
    with:
      environment: ${{ inputs.environment }}

  build-api:
    needs: [tags]
    uses: ./.github/workflows/build-api.yml
    with:
      tag: ${{ needs.tags.outputs.current }}

  build-client:
    needs: [tags]
    uses: ./.github/workflows/build-client.yml
    secrets:
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      SENTRY_CLIENT_AUTH_TOKEN: ${{ secrets.SENTRY_CLIENT_AUTH_TOKEN }}
    with:
      environment: ${{ inputs.environment }}
      tag: ${{ needs.tags.outputs.current }}

  migrate:
    needs: [tags, build-api, build-client]
    uses: ./.github/workflows/migrate.yml
    secrets:
      SCALINGO_SSH_KEY: ${{ secrets.SCALINGO_SSH_KEY }}
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
    with:
      tags_current: ${{ needs.tags.outputs.current }}
      tags_previous: ${{ needs.tags.outputs.previous }}
      environment: ${{ inputs.environment }}

  deploy:
    name: Deploy scalingo
    needs: [tags, migrate]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
    with:
      environment: ${{ inputs.environment }}
      tags_current: ${{ needs.tags.outputs.current }}
      tags_previous: ${{ needs.tags.outputs.previous }}
