name: 'Deploy staging'
permissions:
  contents: read
  packages: read

on:
  push:
    tags:
      - IT[0-9]+S[0-9]
      - IT[0-9]+S[0-9]+-[0-9]+

jobs:
  release:
    uses: ./.github/workflows/release.yml
    secrets:
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
      SENTRY_API_AUTH_TOKEN: ${{ secrets.SENTRY_API_AUTH_TOKEN }}
      SENTRY_CLIENT_AUTH_TOKEN: ${{ secrets.SENTRY_CLIENT_AUTH_TOKEN }}
      SCALINGO_SSH_KEY: ${{ secrets.SCALINGO_SSH_KEY }}
    with:
      environment: staging

  notify-changelog:
    needs: [release]
    runs-on: ubuntu-latest
    env:
      tags_current: ${{ needs.release.outputs.tags_current }}
      tags_previous: ${{ needs.release.outputs.tags_previous }}
      MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-tags: true
          fetch-depth: 200

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: '24.12.0'
          package-manager-cache: false

      - shell: bash
        id: changelog
        run: |
          echo "${tags_current}" ${tags_previous}
          {
            echo 'markdown<<EOF'
            node scripts/changelog ${tags_current} ${tags_previous}
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Outputs changelog
        env:
          CHANGELOG: ${{ steps.changelog.outputs.markdown }}
        run: echo "$CHANGELOG" >> $GITHUB_STEP_SUMMARY

      - name: Notify Mattermost
        if: ${{ env.MATTERMOST_WEBHOOK != '' }}
        env:
          CHANGELOG: ${{ steps.changelog.outputs.markdown }}
          MATTERMOST_WEBHOOK: ${{ env.MATTERMOST_WEBHOOK }}
        run: |
          jq -n --arg text "$CHANGELOG" '{attachments: [
            { text:$text, title:"Changelog", fields: [{ short: true, title: "CC", value: "- @jquagliatini\n- @remi.boureau.lienard"}] }
          ]}' \
            | curl -XPOST -i -H 'Content-type: application/json' -d @- "$MATTERMOST_WEBHOOK"
