name: "Release"

on:
  workflow_call:
    inputs:
      environment:
        description: "'staging' or 'production'"
        required: true
        type: string

    secrets:
      VITE_SENTRY_DSN:
        required: false
      SCALINGO_API_TOKEN:
        required: false
      SENTRY_API_AUTH_TOKEN:
        required: false
      SENTRY_CLIENT_AUTH_TOKEN:
        required: false

jobs:
  build-and-upload-api-artifact:
    uses: ./.github/workflows/build-and-upload-api-artifact.yml
    with:
      tag: "v${{ github.run_number }}"

  build-and-upload-client-artifact:
    uses: ./.github/workflows/build-and-upload-client-artifact.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      tag: "v${{ github.run_number }}"

  deploy:
    name: Deploy scalingo
    needs: [build-and-upload-api-artifact, build-and-upload-client-artifact]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      tag: "v${{ github.run_number }}"
