name: "Deploy production"
permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:

jobs:
  release:
    if: github.ref_type == 'branch' && github.ref_name == 'production'
    uses: ./.github/workflows/release.yml
    secrets:
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
      SENTRY_API_AUTH_TOKEN: ${{ secrets.SENTRY_API_AUTH_TOKEN }}
      SENTRY_CLIENT_AUTH_TOKEN: ${{ secrets.SENTRY_CLIENT_AUTH_TOKEN }}
      SCALINGO_SSH_KEY: ${{ secrets.SCALINGO_SSH_KEY }}
    with:
      environment: production
