name: "Release"

on:
  workflow_call:
    inputs:
      environment:
        description: "'staging' or 'production'"
        required: true
        type: string

    outputs:
      tags_current:
        value: ${{ jobs.tags.outputs.current }}
      tags_previous:
        value: ${{ jobs.tags.outputs.previous }}

    secrets:
      VITE_SENTRY_DSN:
        required: false
      SCALINGO_API_TOKEN:
        required: false
      SENTRY_API_AUTH_TOKEN:
        required: false
      SENTRY_CLIENT_AUTH_TOKEN:
        required: false
      SCALINGO_SSH_KEY:
        required: false

jobs:
  tags:
    uses: ./.github/workflows/tags.yml
    with:
      environment: ${{ inputs.environment }}

  build-api:
    needs: [tags]
    uses: ./.github/workflows/build-api.yml
    with:
      tag: ${{ needs.tags.outputs.current }}

  build-client:
    needs: [tags]
    uses: ./.github/workflows/build-client.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      tag: ${{ needs.tags.outputs.current }}

  migrate:
    needs: [build-api, build-client]
    uses: ./.github/workflows/migrate.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      scalingo_app_name: ${{ vars.SCALINGO_API_APP_NAME }}
      scalingo_region: ${{ vars.SCALINGO_APP_REGION }}

  deploy:
    name: Deploy scalingo
    needs: [tags, build-api, build-client]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      tags_current: ${{ needs.tags.outputs.current }}
      tags_previous: ${{ needs.tags.outputs.previous }}
