name: 'Deploy staging'
permissions:
  contents: read
  packages: read

on:
  push:
    tags:
      - IT[0-9]+S[0-9]
      - IT[0-9]+S[0-9]+-[0-9]+

jobs:
  release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      environment: staging

  notify-changelog:
    needs: [release]
    runs-on: ubuntu-latest
    env:
      tags_current: ${{ needs.release.outputs.tags_current }}
      tags_previous: ${{ needs.release.outputs.tags_previous }}
      MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-tags: true
          fetch-depth: 200

      - name: Use Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: '24.12.0'

      - shell: bash
        id: changelog
        run: |
          echo "${{ env.tags_current }}" ${{ env.tags_previous }}
          {
            echo 'markdown<<EOF'
            node scripts/changelog ${{ env.tags_current }} ${{ env.tags_previous }}
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Outputs changelog
        env:
          CHANGELOG: ${{ steps.changelog.outputs.markdown }}
        run: echo "$CHANGELOG" >> $GITHUB_STEP_SUMMARY

      - name: Notify Mattermost
        if: ${{ env.MATTERMOST_WEBHOOK != '' }}
        env:
          CHANGELOG: ${{ steps.changelog.outputs.markdown }}
          MATTERMOST_WEBHOOK: ${{ env.MATTERMOST_WEBHOOK }}
        run: |
          jq -n --arg text "$CHANGELOG" '{attachments: [
            { text:$text, title:"Changelog", fields: [{ short: true, title: "CC", value: "- @jquagliatini\n- @remi.boureau.lienard"}] }
          ]}' \
            | curl -XPOST -i -H 'Content-type: application/json' -d @- "$MATTERMOST_WEBHOOK"
