name: PR Conventional Commit Validation
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1
        with:
          title_regex: '^[a-z]+\((FON-\d{2,5}|deps|deps-dev)\)!?: [a-z].+$'
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
